topics = [
    # 1–5: Top 5 European Leagues
    "Premier League",
    "La Liga",
    "Serie A",
    "Bundesliga",
    "Ligue 1",

    # 6–25: Top 5 Clubs from Spain, Portugal, France, Germany (5 per country = 20 clubs)
    "Real Madrid",
    "Barcelona",
    "Atletico Madrid",
    "Sevilla",
    "Valencia",
    "Benfica",
    "Porto",
    "Sporting CP",
    "Braga",
    "Vitoria de Guimaraes",
    "Paris Saint Germain",
    "Marseille",
    "Lyon",
    "Monaco",
    "Lille",
    "Bayern Munich",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    "Borussia Monchengladbach",

    # 26–37: 12 Clubs from the Premier League
    "Manchester United",
    "Liverpool",
    "Manchester City",
    "Arsenal",
    "Chelsea",
    "Tottenham Hotspur",
    "Newcastle United",
    "Aston Villa",
    "Everton",
    "West Ham United",
    "Leicester City",
    "Wolverhampton Wanderers",

    # 38–62: Top Players from Last 5–6 Years (25)
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Neymar",
    "Kylian Mbappe",
    "Robert Lewandowski",
    "Kevin De Bruyne",
    "Mohamed Salah",
    "Sadio Mane",
    "Harry Kane",
    "Luka Modric",
    "Karim Benzema",
    "Virgil van Dijk",
    "Erling Haaland",
    "Eden Hazard",
    "Sergio Ramos",
    "Toni Kroos",
    "Antoine Griezmann",
    "Paul Pogba",
    "N'Golo Kante",
    "Romelu Lukaku",
    "Jan Oblak",
    "Manuel Neuer",
    "Marcelo",
    "Thomas Muller",
    "Pierre Emerick Aubameyang",
    "Chiesa",
    "Omar Marmoush",
    "Barcola",
    "Jota",
    "Joao Felix",

    # 63–77: 15 Legends (European Football Greats)
    "Zinedine Zidane",
    "Thierry Henry",
    "Eric Cantona",
    "Maldini",
    "Andrea Pirlo",
    "Xavi Hernandez",
    "Andres Iniesta",
    "Francesco Totti",
    "Iker Casillas",
    "Gianluigi Buffon",
    "Raul Gonzalez",
    "Dennis Bergkamp",
    "Ryan Giggs",
    "Johan Cruyff",
    "George Best",

    # 78–87: 10 Famous European Derbies
    "El Clasico",
    "Madrid Derby",
    "Manchester Derby",
    "Merseyside Derby",
    "North London Derby",
    "Derby della Madonnina",
    "Der Klassiker",
    "Le Classique",
    "Derbi d'Italia",
    "Derby della Capitale",

    # 88–100: 13 Major European/International Tournaments
    "UEFA Champions League",
    "UEFA Europa League",
    "UEFA Europa Conference League",
    "UEFA Super Cup",
    "UEFA Nations League",
    "UEFA Euro",
    "UEFA European Under 21 Championship",
    "UEFA European Under 19 Championship",
    "FIFA World Cup (European Teams)",
    "UEFA Under 17 Championship",
    "Copa del Rey (Spain)",
    "DFB Pokal (Germany)",
    "Coppa Italia (Italy)",

    # 101–140: 40 Additional Current Players from Big Clubs
    "Vinicius",
    "Rodrygo Goes",
    "Federico Valverde",
    "Eduardo Camavinga",
    "Aurelien Tchouameni",
    "Pedri",
    "Lamine Yamal",
    "Gavi",
    "Ronald Araujo",
    "Ansu Fati",
    "Ferran Torres",
    "Jules Kounde",
    "Jude Bellingham",
    "Alessandro Bastoni",
    "Rafael Leao",
    "Tammy Abraham",
    "Sandro Tonali",
    "Lautaro Martinez",
    "Dybala",
    "Victor Osimhen",
    "Khvicha Kvaratskhelia",
    "Dayot Upamecano",
    "Jamal Musiala",
    "Leroy Sane",
    "Kingsley Coman",
    "Christopher Nkunku",
    "Mason Mount",
    "Reece James",
    "Trent Alexander-Arnold",
    "Andy Robertson",
    "Josko Gvardiol",
    "Kai Havertz",
    "Martin Odegaard",
    "Gabriel Martinelli",
    "Bruno Fernandes",
    "Marcus Rashford",
    "Phil Foden",
    "Rodri",
    "Ruben Dias",
    "Darwin Nunez",
    "Achraf Hakimi",
    "Gabriel Jesus"

    # 141–160: Major Awards & Recognitions (20)
    "Ballon d'Or",
    "UEFA Men's Player of the Year",
    "European Golden Shoe",
    "Golden Boy Award",
    "Bravo Award",
    "FIFA FIFPro World XI",
    "PFA Player of the Year",
    "FWA Footballer of the Year",
    "Premier League Golden Boot",
    "Premier League Golden Glove",
    "Zamora Trophy (La Liga)",
    "Pichichi Trophy",
    "Serie A Top Scorer (Capocannoniere)",
    "Bundesliga Torjagerkanone",
    "Ligue 1 Top Scorer",
    "Yashin Trophy",
    "UEFA Champions League Top Scorer",
    "UEFA Defender of the Season",
    "UEFA Midfielder of the Season",
    "UEFA Goalkeeper of the Season",

    # 161–180: Iconic Stadiums in Europe's Top Leagues (20)
    "Camp Nou",
    "Santiago Bernabeu",
    "Old Trafford",
    "Anfield",
    "Etihad Stadium",
    "Emirates Stadium",
    "Tottenham Hotspur Stadium",
    "San Siro",
    "Stamford Bridge"
    "Allianz Arena",
    "Parc des Princes",
    "Stadio Olimpico",
    "Wanda Metropolitano",
    "St James Park",

    # 181–200: 20 More Current Players (Replacing Twitter Accounts)
    "Jack Grealish",
    "Declan Rice",
    "Alexis Mac Allister",
    "Dominik Szoboszlai",
    "Jurrien Timber",
    "Ederson",
    "Alisson Becker",
    "Thiago Alcantara",
    "Cristian Romero",
    "James Maddison",
    "Moussa Diaby",
    "Lucas Paqueta",
    "Manuel Ugarte",
    "Randal Kolo Muani",
    "Garnacho",
    "Kobbie Mainoo",
    "Ousmane Dembele",
    "Matthijs de Ligt",
    "Serge Gnabry",
    "Alphonso Davies",
    "Son Heung Min",
    "Marquinhos"
    "Pep Guardiola",
    "Carlo Ancelotti",
    "Jurgen Klopp",
    "Mikel Arteta",
    "Erik ten Hag",
    "Xavi Hernandez",
    "Simone Inzaghi",
    "Luciano Spalletti",
    "Julian Nagelsmann",
    "Thomas Tuchel",
    "Roberto De Zerbi",
    "Mauricio Pochettino",
    "Luis Enrique",
    "Massimiliano Allegri",
    "Unai Emery",
    "Diego Simeone",
    "Rudi Garcia",
    "Brendan Rodgers",
    "Arne Slot",
    "Graham Potter",
    "Hansi Flick",
    "Goldbridge",
    "Robbie"
]
